source 'http://rubygems.org'
ruby '2.7.0'

gem 'activesupport'
gem 'capybara'
gem 'foreman'
gem 'httparty'
gem 'jwe'
gem 'mail'
gem 'pdf-reader'
gem 'procodile'
gem 'pry'
gem 'rspec'
gem 'selenium-webdriver'
gem 'site_prism'
