source 'http://rubygems.org'
ruby File.read('.ruby-version').chomp

gem 'rspec'
gem 'capybara'
gem 'selenium-webdriver'
gem 'pry'
gem 'mail'
gem 'httparty'
gem 'pdf-reader'
gem 'jwe'
gem 'site_prism'
