#!/bin/sh

for app in datastore-app submitter-app pdf-generator; do
    until docker exec $app wget http://localhost:3000/health -O - | grep healthy; do
        echo "Waiting for ${app} to start accepting traffic...";
        sleep 1
    done
done

for app in runner-app; do
    until docker exec $app wget http://localhost:3000/ping.json -O - | grep APP_SHA; do
        echo "Waiting for ${app} to start accepting traffic...";
        sleep 1
    done
done

echo "All apps accepting traffic";
